<a href="https://colab.research.google.com/github/rissafar/powerbI-Loan-verification/blob/main/Item_Migration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import files
import io

# Upload the Excel file
uploaded = files.upload()

if not uploaded:
    print("No file uploaded. Please upload your Excel file.")
else:
    # Get the file name from the uploaded dictionary (assuming a single file upload)
    file_path = next(iter(uploaded))

    # Specify the name of the main sheet you want to read
    # If not specified, pandas reads the first sheet by default.
    sheet_name = '' # Replace with your actual sheet name, or remove if you want the first sheet

    try:
        # Load the Excel file into a pandas DataFrame from the uploaded content
        # Use header=2 to set the third row (0-indexed) as the header
        df = pd.read_excel(io.BytesIO(uploaded[file_path]), header=2)
        print(f"Successfully loaded data from '{file_path}'")

        # Display the first 5 rows of the DataFrame
        print("First 5 rows of the DataFrame with corrected headers:")
        display(df.head())

    except ValueError as e:
        print(f"Error: {e}. Please check the sheet name or if the file is a valid Excel file.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

Saving Default19_02_2026_10_02_09.xlsx to Default19_02_2026_10_02_09 (4).xlsx
Successfully loaded data from 'Default19_02_2026_10_02_09 (4).xlsx'
First 5 rows of the DataFrame with corrected headers:

,No.,Description,Search Description,Description 2,Base Unit of Measure,Inventory Posting Group,Unit Price,Blocked,Global Dimension 1 Code,Global Dimension 2 Code,...,Ship line ref,Label unit,WIMS Profile,Stack,High / HI,Tie,SCC-14 maintenance,Category Updates,Include in EDI,UN Code
0,MW2 CRATE 1,Package 1 229x181x221 cm 1440 kg,PACKAGE 1 229X181X221 CM 1440 KG,NaN,CRT,PW INV,0,False,NaN,NaN,...,NaN,NaN,NaN,0,0,0,NaN,Always Allow Category Updates,All,NaN
1,MW2 CRATE 10,Box 10 198x124x143 cm 570 kg,BOX 10 198X124X143 CM 570 KG,NaN,CRT,PW INV,0,False,NaN,NaN,...,NaN,NaN,NaN,0,0,0,NaN,Always Allow Category Updates,All,NaN
2,MW2 CRATE 11,Box 11 198x124x143 cm 430 kg,BOX 11 198X124X143 CM 430 KG,NaN,CRT,PW INV,0,False,NaN,NaN,...,NaN,NaN,NaN,0,0,0,NaN,Always Allow Category Updates,All,NaN
3,MW2 CRATE 12,Box 12 350x172x111 cm 532 kg,BOX 12 350X172X111 CM 532 KG,NaN,CRT,PW INV,0,False,NaN,NaN,...,NaN,NaN,NaN,0,0,0,NaN,Always Allow Category Updates,All,NaN
4,MW2 CRATE 13,Package 13 150x130x120 cm 80 kg,PACKAGE 13 150X130X120 CM 80 KG,NaN,CRT,PW INV,0,False,NaN,NaN,...,NaN,NaN,NaN,0,0,0,NaN,Always Allow Category Updates,All,NaN

In [ ]:
columns_to_keep = [
    'Item No',
    'Description',
    'Description 2',
    'UPC Code',
    'Count unit',
    'Alt Unit 1',
    'Convert 0 to 1 factor',
    'Convert 1 to 2 factor',
    'Length',
    'Width',
    'Height',
    'Unit weight',
    'Hazardous'
]

# Filter the DataFrame to keep only the specified columns
df = df[columns_to_keep]

print("DataFrame after keeping only specified columns:")
display(df.head())

DataFrame after keeping only specified columns:

,Item No,Description,Description 2,UPC Code,Count unit,Alt Unit 1,Convert 0 to 1 factor,Convert 1 to 2 factor,Length,Width,Height,Unit weight,Hazardous
0,CRATE 1,Package 1 229x181x221 cm 1440 kg,NaN,NaN,CRT,NaN,0,0,0,0,0,3168,False
1,CRATE 10,Box 10 198x124x143 cm 570 kg,NaN,NaN,CRT,NaN,0,0,0,0,0,1254,False
2,CRATE 11,Box 11 198x124x143 cm 430 kg,NaN,NaN,CRT,NaN,0,0,0,0,0,946,False
3,CRATE 12,Box 12 350x172x111 cm 532 kg,NaN,NaN,CRT,NaN,0,0,0,0,0,1170,False
4,CRATE 13,Package 13 150x130x120 cm 80 kg,NaN,NaN,CRT,NaN,0,0,0,0,0,176,False

In [ ]:

df['Hazardous'] = df['Hazardous'].apply(lambda x: 'Hazardous' if x == True else '')


df.loc[df['Convert 0 to 1 factor'] == 0, 'Convert 0 to 1 factor'] = 1

df.loc[df['Convert 1 to 2 factor'] == 0, 'Convert 1 to 2 factor'] = 1

display(df.head())

/tmp/ipython-input-3171853454.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Hazardous'] = df['Hazardous'].apply(lambda x: 'Hazardous' if x == True else '')

,Item No,Description,Description 2,UPC Code,Count unit,Alt Unit 1,Convert 0 to 1 factor,Convert 1 to 2 factor,Length,Width,Height,Unit weight,Hazardous
0,CRATE 1,Package 1 229x181x221 cm 1440 kg,NaN,NaN,CRT,NaN,1,1,0,0,0,3168,
1,CRATE 10,Box 10 198x124x143 cm 570 kg,NaN,NaN,CRT,NaN,1,1,0,0,0,1254,
2,CRATE 11,Box 11 198x124x143 cm 430 kg,NaN,NaN,CRT,NaN,1,1,0,0,0,946,
3,CRATE 12,Box 12 350x172x111 cm 532 kg,NaN,NaN,CRT,NaN,1,1,0,0,0,1170,
4,CRATE 13,Package 13 150x130x120 cm 80 kg,NaN,NaN,CRT,NaN,1,1,0,0,0,176,

In [ ]:
new_df = pd.DataFrame({
    'SKU': df['Item No'],
    'Description': df['Description'],
    'Description2': df['Description 2'],
    'Min': '',
    'Max': '',
    'Cycle Count': '',
    'ReorderQty': '',
    'Inventory Method': '',
    'Temperature': '',
    'Cost': '',
    'UPC': df['UPC Code'],
    'Track Lot': True,
    'Track Serial': False,
    'Track ExpDate': False,
    'Primary Unit of Measure': df['Count unit'],
    'Packaging Unit': df['Alt Unit 1'],
    'Packing UOM Qty': df['Convert 0 to 1 factor'],
    'Length': df['Length'],
    'Width': df['Width'],
    'Height': df['Height'],
    'Weight': df['Unit weight'],
    'Qualifiers': '',
    'Storage Setup': '',
    'Variable Setup': '',
    'NMFC#': '',
    'Lot Number Required': False,
    'Serial Number Required': False,
    'Serial Number': False,
    'Exp Date Req': False,
    'Enable Cost': False,
    'Cost Required': False,
    'IsHazMat': df['Hazardous'],
    'HazMatID': '',
    'HazMatShippingName': '',
    'HazMatHazardClass': '',
    'HazMatPackingGroup': '',
    'HazMatFlashPoint': '',
    'HazMatLabelCode': '',
    'HazMatFlag': '',
    'Image URL': '',
    'StorageCountScriptTemplateID': '',
    'StorageRates': '',
    'OutboundMobileSerializationBehavior': '',
    'Price': '',
    'TotalQty': (df['Convert 0 to 1 factor'] * df['Convert 1 to 2 factor']),
    'UnitType': 'PALLET'
})

print("New DataFrame created with specified columns:")
display(new_df.head())

New DataFrame created with specified columns:

,SKU,Description,Description2,Min,Max,Cycle Count,ReorderQty,Inventory Method,Temperature,Cost,...,HazMatFlashPoint,HazMatLabelCode,HazMatFlag,Image URL,StorageCountScriptTemplateID,StorageRates,OutboundMobileSerializationBehavior,Price,TotalQty,UnitType
0,CRATE 1,Package 1 229x181x221 cm 1440 kg,NaN,,,,,,,,...,,,,,,,,,1,PALLET
1,CRATE 10,Box 10 198x124x143 cm 570 kg,NaN,,,,,,,,...,,,,,,,,,1,PALLET
2,CRATE 11,Box 11 198x124x143 cm 430 kg,NaN,,,,,,,,...,,,,,,,,,1,PALLET
3,CRATE 12,Box 12 350x172x111 cm 532 kg,NaN,,,,,,,,...,,,,,,,,,1,PALLET
4,CRATE 13,Package 13 150x130x120 cm 80 kg,NaN,,,,,,,,...,,,,,,,,,1,PALLET

In [ ]:
from google.colab import files

# Define the output Excel file name
output_filename = 'new_dataset.xlsx'

# Save the new DataFrame to an Excel file
new_df.to_excel(output_filename, index=False)

# Download the file
files.download(output_filename)

print(f"DataFrame successfully saved to '{output_filename}' and ready for download.")

DataFrame successfully saved to 'new_dataset.xlsx' and ready for download.